### ISSUE TITLE
tslint rule conflict when default exporting interface

### ISSUE THREAD

**Issue by msz** [tallarium/lenz#14]
While making changes in sark, I encountered a tslint rule conflict when doing `export default interface ISomething {}`. prettier wants to insert a semicolon at the end while the `no-extra-semi` rule wants to remove it. I hotfixed it in sark by adding `"no-extra-semi": false` to tslint rules.

**Comment by akatov** [comment]
does this still exist?

**Comment by msz** [comment]
No, I think this got fixed.
